apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "drp.labels" . | nindent 4 }}
type: Opaque
stringData:
  SUPABASE_CONNECTION_STRING: {{ .Values.secrets.supabaseConnectionString | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  SUPABASE_SERVICE_ROLE_KEY: {{ .Values.secrets.supabaseServiceRoleKey | quote }}
  SENDGRID_API_KEY: {{ .Values.secrets.sendgridApiKey | quote }}
  SUPABASE_URL: {{ .Values.secrets.supabaseUrl | quote }}
